---
- hosts: localhost
  vars:
    - vcenter_hostname: vcenter.cloudhat.local
    - vcenter_username: cloudhat@vsphere.local
    - vcenter_password: VMware1!
  
  tasks:  
    - name: Login to the vCenter instance
      uri:
        url: "https://{{ vcenter_hostname }}/api/session"
        force_basic_auth: yes
        method: POST
        user: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        status_code: 201
        validate_certs: no
      register: login
      
    - name: Gather hosts info using REST API
      uri:
        url: "https://{{ vcenter_hostname }}/api/vcenter/host"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        headers:
          vmware-api-session-id: "{{ login.json }}"
      register: hosts_info
      
    - name: Print hosts info
      debug:
          var: hosts_info
